#! /bin/sh

# rabornd 2013/7/11 - init #2, not sure when I first startd using this idea :(
# rabornd 2013/12/7 - changed to use whatismyipaddress.com and added checks on
#                     pressence of tools needed
# rabornd 2014/1/12 - added -h|--help

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]
then
	echo "$0 will try and bounce off of a public resource if possible to get the public egress IP"
	exit 1
fi

# check for needed tools
for cmd in \
	html2text \
	dos2unix \
	wget
do
	check1="`whereis ${cmd} \
	| awk -F\: '{print $2}' \
	| awk '{print $1}'`"
	if [ ! -f "${check1}" ] \
		|| [ "$check1" = "" ] 
	then
		echo "ERROR: Cannot find command '$cmd' ($check1). Please install."
		exit 1
	fi
done

pName="`basename $0`"
oFile="/tmp/${RANDOM}.out"

if [ -f "${oFile}" ]
then
    echo "ERROR: ${oFile} exists. Please remove if needed. Exiting"
    exit 1
fi

wget --user-agent="firefox" -O ${oFile} http://www.whatismyipaddress.com 2>/dev/null
dos2unix ${oFile} 2>/dev/null
html2text ${oFile} \
	| grep -A1 "Your IP" \
	| head -2 \
	| tail -1 \
	| sed "s/ //g"

rm -f ${oFile}
exit 0
